### ISSUE TITLE
group 111 peer review

### ISSUE THREAD

**Issue by xinqiyue** [timchen0326/US_presidential_election_forecast_2024#13]
Summary:
This paper forecasts the 2024 U.S. Presidential Election using multiple linear regression models based on polling data. Key predictors include numeric grade of pollster, poll score, transparency score, sample size, state, and methodology to estimate support for Kamala Harris and Donald Trump. Candidate with more than 270 Electoral College votes is predicted to win the election. However, neither candidate is projected to win the required 270 electoral votes, with Harris predicted to receive 216 and Trump 147. The paper acknowledges limitations such as polling biases and static predictions, suggesting future improvements like incorporating dynamic polling and additional external factors.

Strong positive points:
- The paper’s acknowledgment of its limitations, along with recommendations for future improvements to refine predictions.
- Clearly explain the steps and methodology used when clean data to improve their model. 
- Good structure with subtitles for each section in the paper.
- Use meaningful name for each table and graphs.
- Use diagnostic graphs to analysis each assumption of linear regression. 
- Use multiple cross-references.
- contain comments in script and qmd code so it is easier to read and understand.
- use catalog. 

Critical improvements needed:
- Need to update llm usage along with the llm statement in ReadMe.md
- Need to remove the subtitle if not needed
- The data in section 4 need to be changed to a table. 
- Need to add the reference of data. 
- Only have graph Percentage vs Sample size when illustrating linear regression model of Harris and Trump. May be add more graphs of other predictor variable used. 
- The analysis data should be in parquet format.
- include some graph with all the analysis data showing. 
- Remove unnecessary words like comprehensive, crucial. (found usage in introduction, section2.1, section 2.3 and section 3)

Suggestions for improvement:
- Can add the result of Harris and Trump to the abstract (receive 216 and 147 votes)
- Use more informative commit message. 
- Can add graphs and tables to illustrate the distribution of each variables.
- In section 3.3.1, correct the typo 'Figure X'.
- remove unnecessary files or update them, including 'scripts/02-download_data.R' and 'scripts/07-replication.R'
- Add comments in code of test scripts.
- Update or remove Preamble in 'scripts/06-model_data.R' and 'scripts/05-exploratory_data_analysis.R'
- Maybe provide discussion on why not choosing other predictor variables in Data section.
- Discuss more details like the total sample size of the dataset you are using in the Data section.
- In section 3, list the predictors used instead of saying predictors remain the same.
- Use cross reference in results

Evaluation:
R is appropriately cited: 1/1
Data are appropriately cited: 0/1 no reference of dataset
Class paper: 1/1
LLM usage is documented: 0/1 no llm included yet
Title: 1/2 subtitle need to be removed or updated
Author, date, and repo: 2/2
Abstract: 3/4 should include the key findings
Introduction: 4/4
Estimand: 1/1 
Data: 6/10 Need more graph and table of all the variables
Measurement: 2/4 Can add more about how the data is measured in the measurement section as discussed in the appendix
Model: 7/10 list the predictors used instead of saying predictors remain the same
Results: 7/10 use cross reference in results
Discussion: 10/10 
Prose: 2/6 have typos, use words like comprehensive, crucial
Cross-references: 1/1
Captions: 2/2
Graphs/tables/etc: 2/4 graphs related to linear model and each predictors should be added and section 4 contain unformatted table
Idealized methodology: 10/10
Idealized survey: 4/4
Pollster methodology overview and evaluation: 10/10
Referencing: 1/4 need to add reference of the data
Commits: 1/2 need to have more informative commit message
Sketches: 2/2
Simulation: 4/4
Tests – simulation: 4/4
Tests – actual: 4/4
Parquet: 0/1
Reproducible workflow: 4/4
Miscellaneous: 1/3

Estimated overall mark:
0 out of 126.
Any other comments:
0 since no llm usage
if llm does not give 0, the result would be 97/126

**Comment by stevenli-uoft** [comment]
- For the data section, I have added figures and tables to the appendix to illustrate each variables statistics
- Fixed typos and improved prose
- Removed unnecessary scripts in previous pull request for another issue
- Discussed more detail on variables used in the data section

Final edits and improvements will still be required, but suggested improvements were primarily covered.
