### ISSUE TITLE
group 138 peer review

### ISSUE THREAD

**Issue by tonytto** [timchen0326/US_presidential_election_forecast_2024#14]
Summary

This paper examines prediction of 2024 U.S presidential election using polling data from ‘FiveThirtyEight’. Writers used linear model to explain their prediction and they couldn’t reach to winner of the election since poll datas shows that the election is  too competitive.

Strong positive points
- Graphs are well labeled and explained for readers
- Used variables for model are well explained

Critical improvements needed
1. Erase subtitle if not needed
2. Add LLM usage since READEME mentioned that LLM has been used
3. Dataset is not cited

Suggestions for improvement:
- Develop model section
- Try to avoid using banned words 
- Remove unnecessary files in repo

Evaluation
R appropriately cited: 1 
Data appropriately cited: 0 
Class paper: 1
LLM usage is documented: 0 
Title: 1 
Author, date, and repo: 2 
Abstract: 4  
Introduction: 3 
Estimand: 1 
Data: 6 
Measurement: 3 
Model: 6 
Results: 6 
Discussion: 6 
Prose: 2 
Cross-references: 1 
Captions: 2 
Graphs/tables/etc.: 2 
Idealized methodology: 10 
Idealized survey: 3  
Pollster methodology overview and evaluation: 10 
Referencing: 0 
Commits: 2 
Sketches: 2 
Simulation: 3 
Test: 8 
Parquet: 0 
Reproducible workflow: 4 
Miscellaneous: 3

Estimated overall mark 89/126 (0 since you didn’t put LLM usages)

Any other comments: This is a good first draft. Please develop little more for model and overall writing. More importantly, put your LLM usages before submitting your repo!

**Comment by stevenli-uoft** [comment]
- Improved the simulation script to be more sophisticated and better representative of real polling data. Added more robust tests to the simulated and actual data scripts, ensuring more coverage of tests.
- The unnecessary files in the script folder has also been removed
- Other suggestions for improvement such as the model and banned words will be addressed on other issues with overlapping suggestions.
